//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.13 at 05:03:51 PM CET 
//


package com.opengate.common.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="deliveryCode" type="{}deliveryCode"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deliveryCode"
})
@XmlRootElement(name = "deliveryStatus")
public class DeliveryStatus {

    @XmlElement(required = true)
    protected DeliveryCode deliveryCode;

    /**
     * Gets the value of the deliveryCode property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryCode }
     *     
     */
    public DeliveryCode getDeliveryCode() {
        return deliveryCode;
    }

    /**
     * Sets the value of the deliveryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryCode }
     *     
     */
    public void setDeliveryCode(DeliveryCode value) {
        this.deliveryCode = value;
    }

}
