//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.13 at 05:03:51 PM CET 
//


package com.opengate.common.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.opengate.common.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.opengate.common.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BoolArray }
     * 
     */
    public BoolArray createBoolArray() {
        return new BoolArray();
    }

    /**
     * Create an instance of {@link Uint8 }
     * 
     */
    public Uint8 createUint8() {
        return new Uint8();
    }

    /**
     * Create an instance of {@link Uint8Array.Uint8List }
     * 
     */
    public Uint8Array.Uint8List createUint8ArrayUint8List() {
        return new Uint8Array.Uint8List();
    }

    /**
     * Create an instance of {@link Uint8Array }
     * 
     */
    public Uint8Array createUint8Array() {
        return new Uint8Array();
    }

    /**
     * Create an instance of {@link Int16Array }
     * 
     */
    public Int16Array createInt16Array() {
        return new Int16Array();
    }

    /**
     * Create an instance of {@link Float64Array.Float64List }
     * 
     */
    public Float64Array.Float64List createFloat64ArrayFloat64List() {
        return new Float64Array.Float64List();
    }

    /**
     * Create an instance of {@link Int32 }
     * 
     */
    public Int32 createInt32() {
        return new Int32();
    }

    /**
     * Create an instance of {@link Uint16 }
     * 
     */
    public Uint16 createUint16() {
        return new Uint16();
    }

    /**
     * Create an instance of {@link Payload }
     * 
     */
    public Payload createPayload() {
        return new Payload();
    }

    /**
     * Create an instance of {@link Int16Array.Int16List }
     * 
     */
    public Int16Array.Int16List createInt16ArrayInt16List() {
        return new Int16Array.Int16List();
    }

    /**
     * Create an instance of {@link Float32 }
     * 
     */
    public Float32 createFloat32() {
        return new Float32();
    }

    /**
     * Create an instance of {@link Notification }
     * 
     */
    public Notification createNotification() {
        return new Notification();
    }

    /**
     * Create an instance of {@link EndpointStatus }
     * 
     */
    public EndpointStatus createEndpointStatus() {
        return new EndpointStatus();
    }

    /**
     * Create an instance of {@link Notifications }
     * 
     */
    public Notifications createNotifications() {
        return new Notifications();
    }

    /**
     * Create an instance of {@link Float32Array.Float32List }
     * 
     */
    public Float32Array.Float32List createFloat32ArrayFloat32List() {
        return new Float32Array.Float32List();
    }

    /**
     * Create an instance of {@link Float32Array }
     * 
     */
    public Float32Array createFloat32Array() {
        return new Float32Array();
    }

    /**
     * Create an instance of {@link BoolArray.BoolList }
     * 
     */
    public BoolArray.BoolList createBoolArrayBoolList() {
        return new BoolArray.BoolList();
    }

    /**
     * Create an instance of {@link Endpoint }
     * 
     */
    public Endpoint createEndpoint() {
        return new Endpoint();
    }

    /**
     * Create an instance of {@link Float64Array }
     * 
     */
    public Float64Array createFloat64Array() {
        return new Float64Array();
    }

    /**
     * Create an instance of {@link Int16 }
     * 
     */
    public Int16 createInt16() {
        return new Int16();
    }

    /**
     * Create an instance of {@link DeliveryStatus }
     * 
     */
    public DeliveryStatus createDeliveryStatus() {
        return new DeliveryStatus();
    }

    /**
     * Create an instance of {@link Uint16Array }
     * 
     */
    public Uint16Array createUint16Array() {
        return new Uint16Array();
    }

    /**
     * Create an instance of {@link Int32Array.Int32List }
     * 
     */
    public Int32Array.Int32List createInt32ArrayInt32List() {
        return new Int32Array.Int32List();
    }

    /**
     * Create an instance of {@link Uint16Array.Uint16List }
     * 
     */
    public Uint16Array.Uint16List createUint16ArrayUint16List() {
        return new Uint16Array.Uint16List();
    }

    /**
     * Create an instance of {@link MessageStatus }
     * 
     */
    public MessageStatus createMessageStatus() {
        return new MessageStatus();
    }

    /**
     * Create an instance of {@link Uint32Array.Uint32List }
     * 
     */
    public Uint32Array.Uint32List createUint32ArrayUint32List() {
        return new Uint32Array.Uint32List();
    }

    /**
     * Create an instance of {@link Bool }
     * 
     */
    public Bool createBool() {
        return new Bool();
    }

    /**
     * Create an instance of {@link Ogmessage }
     * 
     */
    public Ogmessage createOgmessage() {
        return new Ogmessage();
    }

    /**
     * Create an instance of {@link Uint32 }
     * 
     */
    public Uint32 createUint32() {
        return new Uint32();
    }

    /**
     * Create an instance of {@link Str }
     * 
     */
    public Str createStr() {
        return new Str();
    }

    /**
     * Create an instance of {@link Int8Array }
     * 
     */
    public Int8Array createInt8Array() {
        return new Int8Array();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link Uint32Array }
     * 
     */
    public Uint32Array createUint32Array() {
        return new Uint32Array();
    }

    /**
     * Create an instance of {@link StrArray.StrList }
     * 
     */
    public StrArray.StrList createStrArrayStrList() {
        return new StrArray.StrList();
    }

    /**
     * Create an instance of {@link Int8 }
     * 
     */
    public Int8 createInt8() {
        return new Int8();
    }

    /**
     * Create an instance of {@link Int32Array }
     * 
     */
    public Int32Array createInt32Array() {
        return new Int32Array();
    }

    /**
     * Create an instance of {@link StrArray }
     * 
     */
    public StrArray createStrArray() {
        return new StrArray();
    }

    /**
     * Create an instance of {@link Float64 }
     * 
     */
    public Float64 createFloat64() {
        return new Float64();
    }

    /**
     * Create an instance of {@link Int8Array.Int8List }
     * 
     */
    public Int8Array.Int8List createInt8ArrayInt8List() {
        return new Int8Array.Int8List();
    }

}
